# Generated by Django 3.2.8 on 2022-01-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0002_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
